### ISSUE TITLE
Push from the right 

### ISSUE THREAD

**Issue by tlm06** [hsynlms/zeynepjs#10]
Hi,

First of all, thank you for your work on this plugin :)

I have one question:
- is it possible to make the menu appear from the right side of the window, instead of the left side?

Thank you once again

**Comment by hsynlms** [comment]
Hi @tlm06 

Yes, it's possible with CSS. Please take a look at below example:
https://github.com/hsynlms/zeynepjs/blob/master/examples/right-menu.html

**Comment by tlm06** [comment]
Thank you for the quick reply, I didn't notice that example :)
