### ISSUE TITLE
The problem is in older browsers

### ISSUE THREAD

**Issue by den1a** [hsynlms/zeynepjs#12]
Hello. Thank you for a great module! Recently I found a problem in an old version of chrome.

https://user-images.githubusercontent.com/45651923/123632277-6d587980-d820-11eb-90ae-484f9ffcd495.mp4

**Comment by hsynlms** [comment]
Hi @den1a 

Thank you!

Could you please give more details about your environment (the plugin version, chrome version, operating system etc,) and if possible a reproduceable example project zip file (all the demo files in the video)?

**Comment by den1a** [comment]
Thank you for your quick response! I downloaded the plugin and the example today from your repository. Chrome Browser 49. Windows 10

On the video, I ran this file.

https://github.com/hsynlms/zeynepjs/blob/master/examples/index.html

**Comment by hsynlms** [comment]
The version of Chrome you are using is really very old :) But I fixed the case.

**Comment by den1a** [comment]
Thanks! Now everything works great!

**Comment by hsynlms** [comment]
Shipped with version 2.2.0
