### ISSUE TITLE
Implementation problem

### ISSUE THREAD

**Issue by oyerohabib** [hsynlms/zeynepjs#3]
Good day 

i am trying to implement this sidebar in my custom code but i am having issues on this

can anyone please help me out

**Comment by hsynlms** [comment]
Could you give more details about your issues and environment information, please? So I can reproduce it in my computer as well.

**Comment by oyerohabib** [comment]
Alright 

Thanks sir

I am actually trying to build an Amazon clone which I would like to integrate your hamburger menu in it 

I have inserted all the codes and made relevant imports where necessary but it still doesn't work. 

This is the GitHub link to my project github.com/oyerohabib/amz/

I would be glad if you can help me with it 

Thanks

**Comment by hsynlms** [comment]
Hello @oyerohabib ,

I checked your project and it seems `zeynepjs` is not initialized (even not loaded) in your HTML files. I did not get it clear what is the problem here. Could you be more specific, please?

**Comment by hsynlms** [comment]
I think your issue is resolved and thus closing the issue.
