### ISSUE TITLE
The offset sub-categories

### ISSUE THREAD

**Issue by den1a** [hsynlms/zeynepjs#5]
Hi. Thank you for a great module! Faced with the problem of displacement.

![Offset](https://user-images.githubusercontent.com/45651923/98204758-b2553600-1f47-11eb-9b20-8320655b1f5d.gif)

**Comment by hsynlms** [comment]
Thank you for your great feedback!

@den1a could you please confirm that the issue has been fixed with v2.1.0 on the master branch? Then I can publish the new version.
